blog/urls.py
from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^$', views.index, name='homepage'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^set_password/$', views.set_password, name='set_password'),
    url(r'^add_book/$', views.add_book, name='add_book'),
    url(r'^add_img/$', views.add_img, name='add_img'),
    url(r'^view_book_list/$', views.view_book_list, name='view_book_list'),
    url(r'^view_book/detail/$', views.detail, name='detail'),
    url(r'^select/$', views.select),
]

untitled5/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles import views
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.static.serve, {'document_root': settings.STATIC_ROOT}, name="static"),
        url(r'^media/(?P<path>.*)$', views.static.serve, {'document_root': settings.MEDIA_ROOT}, name="media")
    ]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class MyUser(models.Model):
    user = models.OneToOneField(User)
    nickname = models.CharField(max_length=16)
    permission = models.IntegerField(default=1)

    def __unicode__(self):
        return self.user.username


class Book(models.Model):
    name = models.CharField(max_length=128)
    price = models.FloatField()
    author = models.CharField(max_length=128)
    publish_date = models.DateField()
    category = models.CharField(max_length=128)

    class META:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Img(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    img = models.ImageField(upload_to='image/%Y/%m/%d/')
    book = models.ForeignKey(Book)

    class META:
        ordering = ['name']

    def __unicode__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse

from blog.models import MyUser, Book, Img
from blog.utils import permission_check


def index(request):
    user = request.user if request.user.is_authenticated() else None
    content = {
        'active_menu': 'homepage',
        'user': user,
    }
    return render(request, 'index.html', content)
def select(request):
    return render(request, 'select.html')

def signup(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == 'POST':
        password = request.POST.get('password', '')
        repeat_password = request.POST.get('repeat_password', '')
        if password == '' or repeat_password == '':
            state = 'empty'
        elif password != repeat_password:
            state = 'repeat_error'
        else:
            username = request.POST.get('username', '')
            if User.objects.filter(username=username):
                state = 'user_exist'
            else:
                new_user = User.objects.create_user(username=username, password=password,
                                                    email=request.POST.get('email', ''))
                new_user.save()
                new_my_user = MyUser(user=new_user, nickname=request.POST.get('nickname', ''))
                new_my_user.save()
                state = 'success'
    content = {
        'active_menu': 'homepage',
        'state': state,
        'user': None,
    }
    return render(request, 'signup.html', content)


def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            state = 'not_exist_or_password_error'
    content = {
        'active_menu': 'homepage',
        'state': state,
        'user': None
    }
    return render(request, 'login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('homepage'))


@login_required
def set_password(request):
    user = request.user
    state = None
    if request.method == 'POST':
        old_password = request.POST.get('old_password', '')
        new_password = request.POST.get('new_password', '')
        repeat_password = request.POST.get('repeat_password', '')
        if user.check_password(old_password):
            if not new_password:
                state = 'empty'
            elif new_password != repeat_password:
                state = 'repeat_error'
            else:
                user.set_password(new_password)
                user.save()
                state = 'success'
        else:
            state = 'password_error'
    content = {
        'user': user,
        'active_menu': 'homepage',
        'state': state,
    }
    return render(request, 'set_password.html', content)


@user_passes_test(permission_check)
def add_book(request):
    user = request.user
    state = None
    if request.method == 'POST':
        new_book = Book(
                name=request.POST.get('name', ''),
                author=request.POST.get('author', ''),
                category=request.POST.get('category', ''),
                price=request.POST.get('price', 0),
                publish_date=request.POST.get('publish_date', '')
        )
        new_book.save()
        state = 'success'
    content = {
        'user': user,
        'active_menu': 'add_book',
        'state': state,
    }
    return render(request, 'add_book.html', content)


def view_book_list(request):
    user = request.user if request.user.is_authenticated() else None
    category_list = Book.objects.values_list('category', flat=True).distinct()
    query_category = request.GET.get('category', 'all')
    if (not query_category) or Book.objects.filter(category=query_category).count() is 0:
        query_category = 'all'
        book_list = Book.objects.all()
    else:
        book_list = Book.objects.filter(category=query_category)

    if request.method == 'POST':
        keyword = request.POST.get('keyword', '')
        book_list = Book.objects.filter(name__contains=keyword)
        query_category = 'all'

    paginator = Paginator(book_list, 5)
    page = request.GET.get('page')
    try:
        book_list = paginator.page(page)
    except PageNotAnInteger:
        book_list = paginator.page(1)
    except EmptyPage:
        book_list = paginator.page(paginator.num_pages)
    content = {
        'user': user,
        'active_menu': 'view_book',
        'category_list': category_list,
        'query_category': query_category,
        'book_list': book_list,
    }
    return render(request, 'view_book_list.html', content)


def detail(request):
    user = request.user if request.user.is_authenticated() else None
    book_id = request.GET.get('id', '')
    if book_id == '':
        return HttpResponseRedirect(reverse('view_book_list'))
    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist:
        return HttpResponseRedirect(reverse('view_book_list'))
    content = {
        'user': user,
        'active_menu': 'view_book',
        'book': book,
    }
    return render(request, 'detail.html', content)


@user_passes_test(permission_check)
def add_img(request):
    user = request.user
    state = None
    if request.method == 'POST':
        try:
            new_img = Img(
                    name=request.POST.get('name', ''),
                    description=request.POST.get('description', ''),
                    img=request.FILES.get('img', ''),
                    book=Book.objects.get(pk=request.POST.get('book', ''))
            )
            new_img.save()
        except Book.DoesNotExist as e:
            state = 'error'
            print(e)
        else:
            state = 'success'
    content = {
        'user': user,
        'state': state,
        'book_list': Book.objects.all(),
        'active_menu': 'add_img',
    }
    return render(request, 'add_img.html', content)

templates/add_book.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}添加图书{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图书</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">书名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_author" class="col-md-3 control-label">作者：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="author" id="id_author">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_category" class="col-md-3 control-label">类型：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="category" id="id_category">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_price" class="col-md-3 control-label">价格：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="price" id="id_price">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_pubdate" class="col-md-3 control-label">出版日期：</label>
                        <div class="col-md-9">
                            <input type="date" class="form-control" required name="publish_date" id="id_pubdate">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/add_img.html
{% extends "base.html" %}
{% block title %}添加图书{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% elif state == 'error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">添加失败</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图片</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">名称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_description" class="col-md-3 control-label">描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="description" id="id_description">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_book" class="col-md-3 control-label">所属书籍：</label>
                        <div class="col-md-9">
                            <select name="book" data-toggle="select" id="id_book" class="form-control select select-primary mrs mbm">
                                {% for book in book_list %}
                                    <option value="{{ book.id }}">{{ book.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_img" class="col-md-3 control-label">图片：</label>
                        <div class="col-md-9">
                            <input type="file" id="id_img" name="img" class="form-control" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
     <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="{% static "css/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="{% static "css/flat-ui.css"  %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="../../dist/js/vendor/html5shiv.js"></script>
      <script src="../../dist/js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <style>
      body {
          padding-bottom: 20px;
          padding-top: 20px;
      }
      .navbar {
          margin-bottom: 20px;
      }
    </style>
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-3">
            <span class="sr-only">Toggle navigation</span>
          </button>
          <a class="navbar-brand" href="{% url 'homepage' %}">主页</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-3">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'view_book_list' %}">查看图书</a></li>
            <li ><a href="{% url 'add_book' %}">添加图书</a></li>
            <li><a href="{% url 'add_img' %}">添加图片</a></li>
           </ul>
          <ul class="nav navbar-nav navbar-right">
               {% if user %}
                    <li><p class="navbar-text">欢迎你&nbsp;&nbsp;<span id="base_name">{{ user.myuser.nickname }}</span></p>
                    </li>
                    <li><a href="{% url 'logout' %}">注销</a></li>
                    <li><a href="{% url 'set_password' %}">修改密码</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">注册</a></li>
                    <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
    </div>
    <div class="container">
      <blockquote class="pull-right">
        <p>书籍是人类进步的阶梯</p>
        <small>————<cite title="Source Title">高尔基</cite></small>
      </blockquote>
    </div>
    {% block content %}{% endblock %}
    <!-- /.container-fluid -->
<!-- footer -->
<footer class="footer" role="contentinfo">
    <hr>
    <div class="container">
        <p class="text-center">©All rights reserved</p>
        <h5 class="text-center"> Powered by&nbsp;<a href="http://imshen.top/">IM Shen</a></h5>
    </div>
</footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "js/vendor/jquery.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/flat-ui.min.js" %}"></script>
     <script src="{% static "assets/js/application.js" %}"></script>


  </body>
</html>

templates/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}查看图书{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-5">
                    {% if book.img_set.all %}
                        <div id="carousel-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for img in book.img_set.all %}
                                    <li data-target="#carousel-generic" data-slide-to="{{ forloop.counter0 }}"
                                        {% if forloop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                {% for img in book.img_set.all %}
                                    <div {% if forloop.first %}class="item active"{% else %}class="item"{% endif %}>
                                        <img class="img-rounded" src="{% url 'media' img.img %}">
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    {% else %}
                        <p class="text-center">暂无图片</p>
                    {% endif %}
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <h2 class="text-center">{{ book.name }}</h2>
                    <br>
                    <h3>作者：{{ book.author }}</h3>
                    <h3>类别：{{ book.category }}</h3>
                    <h3>出版日期：{{ book.publish_date|date:"Y-m-d" }}</h3>
                    <h3>价格：{{ book.price|floatformat:2 }}</h3>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}图书管理{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
                <h2>&emsp;&emsp;这是主页面</h2>
            </div>
        </div>
    </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}登陆{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'not_exist_or_password_error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户不存在或密码错误</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请登陆</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_password" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">登陆</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/set_password.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}修改密码{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'password_error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">密码错误</h2>
                    </div>
                {% elif state == 'repeat_error' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码重复错误</h2>
                    </div>
                {% elif state == 'empty' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码不能为空</h2>
                    </div>
                {% elif state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">修改成功</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">修改密码</h1>
                    <div class="form-group">
                        <label for="id_old" class="col-md-3 control-label">原始密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="old_password" id="id_old">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_new" class="col-md-3 control-label">新密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="new_password" id="id_new">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_new_re" class="col-md-3 control-label">重复密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="repeat_password" id="id_new_re">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}注册{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">注册成功！</h2>
                    </div>
                {% elif state == 'repeat_error' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码重复错误</h2>
                    </div>
                {% elif state == 'empty' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码不能为空</h2>
                    </div>
                {% elif state == 'user_exist' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户已经存在</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请注册</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                            <span class="help-block">用于登陆，可以包括大小写字母和下划线。</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">昵称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="nickname" id="id_name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_passwd" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_passwd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_repasswd" class="col-md-3 control-label">重复密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="repeat_password"
                                   id="id_repasswd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_email" class="col-md-3 control-label">电子邮件：</label>
                        <div class="col-md-9">
                            <input type="email" class="form-control" required name="email" id="id_email">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit" id="id_submit">注册</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock %}